version: '3.8'

services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PW}
      ME_CONFIG_MONGODB_URL: ${MONGO_DOCKER_URL}
      ME_CONFIG_BASICAUTH: false
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local